### PR TITLE
Update to python3 plugin (3.8 recommended), drop python2 support, fix use of "Setting" to be "Settings" from the current binaryninja-api source

### PR DESCRIPTION
**Pull request by stvn1337**
Binary Ninja plugins are being updated to focus on Python3, this update does this. Also, it fixes the Setting changed to Settings issue from binaryninja-api. This pull request has no additional package requirements than the original release, it does, however, drops support for python2. If you want me to utilize futurize/poetry packages (like builtins) to make it compatible between python2 and python 3.8.1  users I can do that, it will require additional dependencies be installed by the user though. My original pull request (now closed) was the beginnings of cross-compatibility between python2/3 but to reduce install requirements I chose to reduce it to a python3 only plugin. Let me know your thoughts on this.

### CODE REVIEW

**Comment by stvn1337** [comment]
Okay, after testing I found one more bug with not registering Settings module before use. I made the changes to register the scoped Settings module in init and fixed the scope on the get_string/set_string calls. This PR has been tested and should be ready for release.

**Comment by chame1eon** [comment]
Hi! Thanks very much for doing all this. Looks great to me. I am more than happy to get rid of the python 2 support. At the time I wrote it, only Python 2 was the supported default so used that rather than 3. Thanks again, will merge it now.

**Comment by stvn1337** [comment]
Awesome, you're welcome. I have been playing around with it all day. It seems to work well, even with Python version 3.8.1.  Do you mind doing a release for the plugin manager?

**Comment by chame1eon** [comment]
No problem. I have just now filed the issue with the community plugin folder. Hopefully it won't take too long.

**Comment by chame1eon** [comment]
Just been merged into the plugin folder. Should be available through the PluginManager now.

**Pull request merged**
